# Generated by Django 2.0.7 on 2018-08-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alugado', models.DateField()),
                ('devolucao', models.DateField()),
                ('status', models.CharField(choices=[('Alugado', 'Alugado'), ('Reservado', 'Reservado'), ('Encerrado', 'Encerrado'), ('Completo', 'Completo')], default='Completo', max_length=10)),
            ],
            options={
                'db_table': 'Alugar',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('placa', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=180)),
                ('Bairro', models.CharField(max_length=60)),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='alugar',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carro'),
        ),
        migrations.AddField(
            model_name='alugar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
    ]
