# Generated by Django 2.0.7 on 2018-08-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alugar',
            options={'verbose_name_plural': 'Alugar'},
        ),
        migrations.AlterModelTable(
            name='alugar',
            table=None,
        ),
    ]
