# Generated by Django 2.0.7 on 2018-08-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180821_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Key'),
        ),
    ]
