# Generated by Django 2.0.7 on 2018-08-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180821_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='key',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
