# Generated by Django 2.0.7 on 2018-08-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180826_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alugar',
            name='cliente',
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Alugar',
        ),
    ]
