# Generated by Django 2.0.7 on 2018-09-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_movmensalista'),
    ]

    operations = [
        migrations.AddField(
            model_name='movmensalista',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
