# Generated by Django 2.0.7 on 2018-09-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=60)),
                ('news', models.TextField()),
            ],
        ),
    ]
