# Generated by Django 2.0.7 on 2018-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
