# Generated by Django 2.0.7 on 2018-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_new_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='published',
        ),
        migrations.AddField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=12),
        ),
    ]
