# Generated by Django 2.0.7 on 2018-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180908_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tags',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
